### ISSUE TITLE
Migration out of Clojure Contrib

### ISSUE THREAD

**Issue by cemerick** [clojure-emacs/nREPL#1]
As discussed on the [Clojure google group](https://groups.google.com/d/msg/clojure/6SX7q39lK90/E9RsccByAwAJ), maintenance of nREPL is moving out of the Clojure Contrib umbrella. To restate the rationale from that thread:

<blockquote>

1. nREPL is an essential bit of infrastructure in Clojure tooling
2. On balance, I have neglected the project in recent years, to the detriment of all of the users of the aforementioned tooling.
3. On balance, contributors and potential contributors have been less involved (or turned away entirely) because of the well-known friction that comes with the contrib process and requirements. (tbh, this is a factor in #2, though not the majority)
4. No one (least of all me) would object to nREPL having its contribution process managed through github or gitlab.

So basically everyone wants nREPL to be a "regular" project, and subject to and beneficiary of the same expectations as 99.9% of all of the other OSS projects we all interact with daily.

</blockquote>

To move forward, I've decided to "reboot" the project; i.e. to reconstitute it as a standalone effort without any legacy tying it to its time within the Contrib system. Simply forking back to my repo here would be far easier in the short term, but I prefer a reboot at this point because, as I state [later on in the aforementioned Google Groups thread](https://groups.google.com/d/msg/clojure/6SX7q39lK90/guQ53m77AAAJ):

> Do I want to maintain explanations of the answers to [questions regarding the heritage and lingering impact of the Contrib process and Contributor's Agreement] for a (fork of a) project that's no longer within contrib? Most definitely not.

The vast majority of the commits in the history at [tools.nrepl](https://github.com/clojure/tools.nrepl/) are mine, and the project's license will remain EPL, so this should a pretty straightforward task. I will solicit agreement from all material contributors to the [tools.nrepl](https://github.com/clojure/tools.nrepl/) project in a subtask listed below, which will simply establish that their contributions are available under EPL (whereas to date, they are only available in a "CA-encumbered" state since they were provided via the Contrib process).

## Migration TODOs

* [X] Obtain agreement from material contributors to [tools.nrepl](https://github.com/clojure/tools.nrepl/) that their work is available under EPL-only terms (#2)
* [X] Reconstruct commit history to include only those contributors' work (this will drop things like minor build process changes, commits by the `build.clojure.org` buildbots, etc)
* [X] Change maven coordinates (back) to `com.cemerick/nrepl`
* [X] Tweak up build process to deploy to Maven central without using the Contrib parent POM, etc
* [X] Cut a release matching `[org.clojure/tools.nrepl "0.2.13"]` in every material way
* [X] Grant commit to additional key contributors
* [X] 🎉 ❗️ 
* [X] Make more sweet REPLs and other tools 😄

**Comment by bbatsov** [comment]
>  Cut a release matching [org.clojure/tools.nrepl "0.2.13"] in every material way

Do you have any timeline in mind for that pivotal moment? :-)

**Comment by xiongtx** [comment]
Anything in particular this is waiting for?

**Comment by bbatsov** [comment]
@xiongtx Not anymore. Time to make this happen!
