### ISSUE TITLE
Consider transfering the repo

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/nREPL#21]
Hey Chas!

I don't mean to be pushy or something, but I was really looking forward to nREPL 0.3 (and mostly to what would follow afterwards). I also see you probably didn't have time for nREPL 0.3 recently. Would be open to just transferring the repo to `clojure-emacs` so we can maintain it there, as we did with piggieback? I think it'd be in the project's best interest if we have more people sharing its maintenance.

**Comment by cemerick** [comment]
It is done, as you can see. You are right that I'm very involved elsewhere. Thanks to everyone for picking up where I left off. ❤️
